package com.facebook.ads;

import com.facebook.ads.internal.settings.C2159a.C2158a;

public enum AudienceNetworkActivity$Type {
    INTERSTITIAL_WEB_VIEW(C2158a.INTERSTITIAL_WEB_VIEW),
    INTERSTITIAL_NATIVE_VIDEO(C2158a.INTERSTITIAL_NATIVE_VIDEO),
    INTERSTITIAL_NATIVE_IMAGE(C2158a.INTERSTITIAL_NATIVE_IMAGE),
    INTERSTITIAL_NATIVE_CAROUSEL(C2158a.INTERSTITIAL_NATIVE_CAROUSEL),
    FULL_SCREEN_VIDEO(C2158a.FULL_SCREEN_VIDEO),
    REWARDED_VIDEO(C2158a.REWARDED_VIDEO),
    BROWSER(C2158a.BROWSER);
    
    C2158a f3980a;

    private AudienceNetworkActivity$Type(C2158a c2158a) {
        this.f3980a = c2158a;
    }
}
